# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
                ('project_description', models.TextField()),
                ('project_status', models.CharField(max_length=10)),
                ('project_likes', models.IntegerField()),
                ('project_level', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=55)),
                ('skill_status', models.CharField(max_length=10)),
                ('skill_description', models.TextField()),
                ('skill_type', models.CharField(max_length=10)),
                ('skill_area', models.CharField(max_length=10)),
                ('skill_level', models.CharField(max_length=10)),
                ('skill_value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('skill_likes', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Project')),
            ],
        ),
    ]
